<?php

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 */
function d3_migrate_album_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $album = $row->getSourceProperty('album');
  $artist = $row->getSourceProperty('musician');

  $fv = fopen('/var/www/html/web/modules/custom/d3/artifacts/music.csv', 'r');
  if ($fv === FALSE) {
    return;
  }
  $songs = [];
  while ($data = fgetcsv($fv)) {
    if ($album == $data[1] && $artist == $data[2]) {
      $songs[] = $data[0];
    }
  }
  $row->setSourceProperty('calculated_songs', $songs);
}
